# fly.toml file generated for speedrun-guide on 2023-05-10T04:30:24-05:00

app = "speedrun-guide"
primary_region = "iad"

[build]
    dockerfile = "Dockerfile"

[[services]]
    http_checks = []
    internal_port = 8043
    protocol = "tcp"
    processes = ["app"]
    script_checks = []
    auto_start_machines = true
    auto_stop_machines = true

    [services.concurrency]
        hard_limit = 250
        soft_limit = 10
        type = "connections"

    [[services.ports]]
        handlers = ["http"]
        port = 80
        force_https = false

    [[services.tcp_checks]]
        grace_period = "1s"
        interval = "15s"
        restart_limit = 0
        timeout = "2s"